apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-sample
  namespace: nodejs-sample
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nodejs-sample
  template:
    metadata:
      labels:
        app: nodejs-sample
    spec:
      containers:
        - name: nodejs-sample
          image: 1234samue/nodejs-sample:main-59f04191ac53d5eb4e1e08109c74d31b12e6d518
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
