apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-sample
  namespace: nodejs-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-sample
  template:
    metadata:
      labels:
        app: nodejs-sample
    spec:
      containers:
        - name: nodejs-sample
          image: '1234samue/nodejs-sample:main-1c602989155ad06d4f5f0673ce814da6c83b5e5b'
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
