apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-sample
  namespace: nodejs-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-sample
  template:
    metadata:
      labels:
        app: nodejs-sample
    spec:
      containers:
        - name: nodejs-sample
          image: '1234samue/nodejs-sample:main-db1fad5653e47d300ddd2343571697ad0d321f31'
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
