apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-sample
  namespace: nodejs-sample
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nodejs-sample
  template:
    metadata:
      labels:
        app: nodejs-sample
    spec:
      containers:
        - name: nodejs-sample
          image: 1234samue/nodejs-sample:main-d09f1774e9fa110d672e8f54d3164e696716f2cb
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
