# Service YAML
apiVersion: v1 
kind: Service
metadata:
  name: nodejs-sample-service
  namespace: nodejs-sample
spec:
  selector:
    app: Node.js
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
