apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: example-argocd
    app.kubernetes.io/name: example-argocd-server
    app.kubernetes.io/part-of: argocd
  name: example-argocd-server
  namespace: olm
  ownerReferences:
  - apiVersion: argoproj.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ArgoCD
    name: example-argocd
    uid: 0e111e71-e1e1-4084-b331-a370361af7e4
  resourceVersion: "2701"
  uid: c62f38df-377f-4647-a26d-1dbb1a82cd03
spec:
  clusterIP: 10.97.53.60
  clusterIPs:
  - 10.97.53.60
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: example-argocd-server
  sessionAffinity: None
  type: ClustrIP
status:
  loadBalancer: {}
